I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/common5.rpy", line 60, in script
    Girl_2 "Yeah, they assume you miss a lot for good reason... You could get suspended if they knew you were just lazy."
Exception: Sayer 'Girl_2' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/common5.rpy", line 60, in script
    Girl_2 "Yeah, they assume you miss a lot for good reason... You could get suspended if they knew you were just lazy."
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Girl_2' is not defined.

Darwin-16.5.0-x86_64-i386-64bit
Ren'Py 6.99.12.2.2029
WIP2 0.04
